<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mola_ct_lio</name>
  <version>0.1.0</version>
  <description>Continuous-time LiDAR-inertial odometry for MOLA, with mp2p_icp matching over incremental point maps</description>

  <maintainer email="jlblanco@ual.es">Jose Luis Blanco-Claraco</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
